name: DigitalCane
options:
  bundleIdPrefix: com.assistiveai
  deploymentTarget:
    iOS: 16.0
targets:
  DigitalCane:
    type: application
    platform: iOS
    sources: [DigitalCane/App, DigitalCane/Services, DigitalCane/Resources]
    # info:
    #   path: DigitalCane/Info.plist
    #   properties:
    #     CFBundleShortVersionString: "1.0"
    settings:
      base:
        PRODUCT_NAME: "디지털케인"
        PRODUCT_BUNDLE_IDENTIFIER: kr.ac.kaist.assistiveailab.DigitalCane
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleDisplayName: "디지털케인"
        INFOPLIST_KEY_CFBundleName: "디지털케인"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "목적지 음성 입력을 위해 음성 인식이 필요합니다."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "음성 명령을 듣기 위해 마이크 접근이 필요합니다."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "현재 위치 기반 대중교통경로안내를 제공하기 위해 위치 정보가 필요합니다."
